id: PC216F458
initial_creation_type: input
source_metadata:
  Title: Pratityasamutpadahrdaya and aryadharmadhatugarbhavivarana
  Editor: Namdrol, Gyaltsen
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1997'
  Pratītyasamutpādahṛdayavyākhyānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:40:29.800048'
last_modified_at: '2022-03-08T16:40:29.800055'
